grainsCOMP = {
"C" : {"reactants": ['C'], "reactants_amount" : [1]}, 
"Fe" : {"reactants": ['Fe'], "reactants_amount" : [1]},
"FeS" : {"reactants": ['Fe','S'], "reactants_amount" : [1,1]},
"Si" : {"reactants": ['Si'], "reactants_amount" : [1]},
"Ti" : {"reactants": ['Ti'], "reactants_amount" : [1]},
"Cr" : {"reactants": ['Cr'], "reactants_amount" : [1]},
"Co" : {"reactants": ['Co'], "reactants_amount" : [1]},
"Ni" : {"reactants": ['Ni'], "reactants_amount" : [1]},
"SiO2" : {"reactants": ['Si','O'], "reactants_amount" : [1,2]},
"MgO" : {"reactants": ['Mg','O'], "reactants_amount" : [1,1]},
"Fe3O4" : {"reactants": ['Fe','O'], "reactants_amount" : [3,4]},
"FeO" : {"reactants": ['Fe','O'], "reactants_amount" : [1,1]},
"SiC" : {"reactants": ['Si','C'], "reactants_amount" : [1,1]},
"TiC" : {"reactants": ['Ti','C'], "reactants_amount" : [1,1]},
"Al2O3" : {"reactants": ['Al','O'], "reactants_amount" : [2,3]},
"MgSiO3" : {"reactants": ['Mg','Si','O'], "reactants_amount" : [1,1,3]},
}
